{
 "title": "Market Data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "epam-timebase-datasource" },
   {
    "name": "stream",
    "query": "select key as '__var' array join streams().key as 'key'"
   },
   {
    "name": "symbol",
    "query": "select s as '__var' array join symbols('$stream') as 's'"
   },
   { "name": "TradeType", "query": "TradeEntry,BittrexTradeEntry" }
  ]
 },
 "panels": [
  {
   "title": "Bars",
   "type": "ilgizar-candlestick-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawQuery": "/* one-minute bars based on trades */\nWITH entries[this is $TradeType] as 'entries'\nSELECT\nfirst{}(entries[0].price) as 'open',\nlast{}(entries[-1].price) as 'close',\nmax{}(max(entries.price)) as 'high',\nmin{}(min(entries.price)) as 'low'\nFROM $stream\nOVER TIME($__interval)\nWHERE symbol == '$symbol'\nAND notEmpty(entries)\n",
     "requestType": "TIMESERIES"
    }
   ]
  },
  {
   "title": "Indicators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "/* one-minute bars based on trades */\nWITH entries[this is $TradeType] as 'entries',\nsum(entries.price * entries.size) / sum(entries.size) as 'avgPrice',\nbollinger{}(avgPrice) as 'bollinger'\nSELECT\navgPrice,\nsma{timePeriod: 1h}(avgPrice) as 'sma-1h',\ncma{}(avgPrice) as 'cma',\nema{period: 14}(avgPrice) as 'ema-14',\nbollinger.upperBand,\nbollinger.middleBand,\nbollinger.lowerBand\nFROM $stream\nOVER TIME($__interval)\nWHERE symbol == '$symbol'\nAND notEmpty(entries)\n"
    }
   ]
  },
  {
   "title": "Bars",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "/* one-minute bars based on trades */\nWITH entries[this is $TradeType] as 'entries'\nSELECT\nsum{}(sum(entries.size)) as 'volume'\nFROM $stream\nOVER TIME($__interval)\nWHERE symbol == '$symbol'\nAND notEmpty(entries)\n",
     "requestType": "TIMESERIES"
    }
   ]
  },
  {
   "title": "Current $symbol price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "/* one-minute bars based on trades */\nWITH entries[this is L2EntryNew] as 'entries',\nsum(entries.price * entries.size) / sum(entries.size) as 'avgPrice'\nSELECT\navgPrice\nFROM $stream\nOVER TIME($__interval)\nWHERE symbol == '$symbol'\nAND notEmpty(entries)\n"
    }
   ]
  },
  {
   "title": "Current Bid $symbol price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "/* one-minute bars based on trades */\nwith (entries[this is L2EntryNew] as array(L2EntryNew))[this.side == BID] as 'entries',\nsum(entries.price * entries.size) / sum(entries.size) as 'bidPrice'\nSELECT\nbidPrice\nFROM $stream\nOVER TIME($__interval)\nWHERE symbol == '$symbol'\nAND notEmpty(entries)\n"
    }
   ]
  },
  {
   "title": "Current Ask $symbol price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "/* one-minute bars based on trades */\nwith (entries[this is L2EntryNew] as array(L2EntryNew))[this.side == ASK] as 'entries',\nsum(entries.price * entries.size) / sum(entries.size) as 'askPrice'\nSELECT\naskPrice\nFROM $stream\nOVER TIME($__interval)\nWHERE symbol == '$symbol'\nAND notEmpty(entries)\n"
    }
   ]
  }
 ]
}