{
 "title": "TimeBase overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "epam-timebase-datasource" },
   {
    "name": "stream",
    "query": "select s.key as '__var' array join streams() as s"
   },
   {
    "name": "symbol",
    "query": "select s as '__var' array join symbols('$stream') as 's'"
   },
   {
    "name": "type",
    "query": "select t.name as '__var' array join streams()[this.key == '$stream'].topTypes as 't'"
   }
  ]
 },
 "panels": [
  { "title": "Overall info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Streams",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "rawQuery": "select s.key as 'key', s.description as 'description',  s.topTypes.name as 'topTypes' array join streams() as 's'"
    }
   ]
  },
  {
   "title": "Streams count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawQuery": "select size(streams())" }
   ]
  },
  {
   "title": "Stateful functions",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawQuery": "select \nf.id as 'function', \nf.initArguments.name as 'initArgs', f.initArguments.dataType.baseName as 'initArgTypes', \nf.arguments.dataType.baseName as 'argTypes'\narray join stateful_functions() as f"
    }
   ]
  },
  {
   "title": "Stateless functions",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawQuery": "select \nf.id as 'function', \nf.arguments.dataType.baseName as 'argTypes'\narray join stateless_functions() as f"
    }
   ]
  },
  { "title": "Selected stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "'$stream' types",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "rawQuery": "select t.name as 'typeName' array join streams()[this.key == '$stream'].topTypes as 't'"
    }
   ]
  },
  {
   "title": "Fields from $type",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "rawQuery": "select field.name, field.dataType.baseName as 'fieldType', field.dataType.encoding as 'encoding' array join streams()[this.key == '$stream'].topTypes.dataFields as 'field'"
    }
   ]
  }
 ]
}