name: Release

on:
  push:
    tags:
    - '*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: zip -r epam-timebase-datasource.zip dist/
        with:
          path: epam-timebase-datasource.zip
  Release:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "epam-timebase-datasource.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
