name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: node:12-alpine3.12
    if: !contains( github.event.head_commit.message, RobotBuild )
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: node_modules
          restore-keys: |
            node_modules
      - name: Build with yarn
        run: yarn install && yarn build
