name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    if: "!contains( github.event.head_commit.message, 'RobotBuild' )"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          # Check all markdown and html files in repo (default) './**/*.html'
          args: --verbose --exclude-all-private --no-progress 'README.md'
          # Use json as output format (instead of markdown)
          # format: json
          # Use different output file path
          # output: /tmp/foo.txt
          # Fail action on broken links
          fail: true