name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    if: "!contains( github.event.head_commit.message, 'RobotBuild' )"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
